<template>
  <Wrapper>
    <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Natus mollitia nulla unde quidem voluptas nesciunt cupiditate eos voluptatem repellat animi, velit dolore? Illum, reprehenderit assumenda.</p>
    <h4>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Magnam porro hic quisquam molestiae consequatur. Quia eligendi perspiciatis perferendis voluptatibus earum excepturi cum blanditiis dolorem quod temporibus, quibusdam deserunt. Perspiciatis dignissimos natus excepturi praesentium corporis dolor error ea veritatis assumenda eveniet optio cupiditate, corrupti eaque odit ullam veniam nulla harum dolorem commodi id? Earum, rerum? Placeat, quidem voluptatum magni dolores eaque qui natus ad! Ipsum ea quia aperiam minus, deserunt recusandae soluta id animi cumque ab optio dolor quidem perspiciatis maxime nam totam non quae. In, deserunt sapiente. Voluptas inventore temporibus aspernatur itaque nisi labore mollitia, ipsam sapiente et necessitatibus nam.</h4>
    <h4>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Magnam porro hic quisquam molestiae consequatur. Quia eligendi perspiciatis perferendis voluptatibus earum excepturi cum blanditiis dolorem quod temporibus, quibusdam deserunt. Perspiciatis dignissimos natus excepturi praesentium corporis dolor error ea veritatis assumenda eveniet optio cupiditate, corrupti eaque odit ullam veniam nulla harum dolorem commodi id? Earum, rerum? Placeat, quidem voluptatum magni dolores eaque qui natus ad! Ipsum ea quia aperiam minus, deserunt recusandae soluta id animi cumque ab optio dolor quidem perspiciatis maxime nam totam non quae. In, deserunt sapiente. Voluptas inventore temporibus aspernatur itaque nisi labore mollitia, ipsam sapiente et necessitatibus nam.</h4>
    <h4>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Magnam porro hic quisquam molestiae consequatur. Quia eligendi perspiciatis perferendis voluptatibus earum excepturi cum blanditiis dolorem quod temporibus, quibusdam deserunt. Perspiciatis dignissimos natus excepturi praesentium corporis dolor error ea veritatis assumenda eveniet optio cupiditate, corrupti eaque odit ullam veniam nulla harum dolorem commodi id? Earum, rerum? Placeat, quidem voluptatum magni dolores eaque qui natus ad! Ipsum ea quia aperiam minus, deserunt recusandae soluta id animi cumque ab optio dolor quidem perspiciatis maxime nam totam non quae. In, deserunt sapiente. Voluptas inventore temporibus aspernatur itaque nisi labore mollitia, ipsam sapiente et necessitatibus nam.</h4>
    <h4>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Magnam porro hic quisquam molestiae consequatur. Quia eligendi perspiciatis perferendis voluptatibus earum excepturi cum blanditiis dolorem quod temporibus, quibusdam deserunt. Perspiciatis dignissimos natus excepturi praesentium corporis dolor error ea veritatis assumenda eveniet optio cupiditate, corrupti eaque odit ullam veniam nulla harum dolorem commodi id? Earum, rerum? Placeat, quidem voluptatum magni dolores eaque qui natus ad! Ipsum ea quia aperiam minus, deserunt recusandae soluta id animi cumque ab optio dolor quidem perspiciatis maxime nam totam non quae. In, deserunt sapiente. Voluptas inventore temporibus aspernatur itaque nisi labore mollitia, ipsam sapiente et necessitatibus nam.</h4>
    <h4>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Magnam porro hic quisquam molestiae consequatur. Quia eligendi perspiciatis perferendis voluptatibus earum excepturi cum blanditiis dolorem quod temporibus, quibusdam deserunt. Perspiciatis dignissimos natus excepturi praesentium corporis dolor error ea veritatis assumenda eveniet optio cupiditate, corrupti eaque odit ullam veniam nulla harum dolorem commodi id? Earum, rerum? Placeat, quidem voluptatum magni dolores eaque qui natus ad! Ipsum ea quia aperiam minus, deserunt recusandae soluta id animi cumque ab optio dolor quidem perspiciatis maxime nam totam non quae. In, deserunt sapiente. Voluptas inventore temporibus aspernatur itaque nisi labore mollitia, ipsam sapiente et necessitatibus nam.</h4>
    <h4>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Magnam porro hic quisquam molestiae consequatur. Quia eligendi perspiciatis perferendis voluptatibus earum excepturi cum blanditiis dolorem quod temporibus, quibusdam deserunt. Perspiciatis dignissimos natus excepturi praesentium corporis dolor error ea veritatis assumenda eveniet optio cupiditate, corrupti eaque odit ullam veniam nulla harum dolorem commodi id? Earum, rerum? Placeat, quidem voluptatum magni dolores eaque qui natus ad! Ipsum ea quia aperiam minus, deserunt recusandae soluta id animi cumque ab optio dolor quidem perspiciatis maxime nam totam non quae. In, deserunt sapiente. Voluptas inventore temporibus aspernatur itaque nisi labore mollitia, ipsam sapiente et necessitatibus nam.</h4>
    <h4>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Magnam porro hic quisquam molestiae consequatur. Quia eligendi perspiciatis perferendis voluptatibus earum excepturi cum blanditiis dolorem quod temporibus, quibusdam deserunt. Perspiciatis dignissimos natus excepturi praesentium corporis dolor error ea veritatis assumenda eveniet optio cupiditate, corrupti eaque odit ullam veniam nulla harum dolorem commodi id? Earum, rerum? Placeat, quidem voluptatum magni dolores eaque qui natus ad! Ipsum ea quia aperiam minus, deserunt recusandae soluta id animi cumque ab optio dolor quidem perspiciatis maxime nam totam non quae. In, deserunt sapiente. Voluptas inventore temporibus aspernatur itaque nisi labore mollitia, ipsam sapiente et necessitatibus nam.</h4>
    <h4>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Magnam porro hic quisquam molestiae consequatur. Quia eligendi perspiciatis perferendis voluptatibus earum excepturi cum blanditiis dolorem quod temporibus, quibusdam deserunt. Perspiciatis dignissimos natus excepturi praesentium corporis dolor error ea veritatis assumenda eveniet optio cupiditate, corrupti eaque odit ullam veniam nulla harum dolorem commodi id? Earum, rerum? Placeat, quidem voluptatum magni dolores eaque qui natus ad! Ipsum ea quia aperiam minus, deserunt recusandae soluta id animi cumque ab optio dolor quidem perspiciatis maxime nam totam non quae. In, deserunt sapiente. Voluptas inventore temporibus aspernatur itaque nisi labore mollitia, ipsam sapiente et necessitatibus nam.</h4>
    <h4>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Magnam porro hic quisquam molestiae consequatur. Quia eligendi perspiciatis perferendis voluptatibus earum excepturi cum blanditiis dolorem quod temporibus, quibusdam deserunt. Perspiciatis dignissimos natus excepturi praesentium corporis dolor error ea veritatis assumenda eveniet optio cupiditate, corrupti eaque odit ullam veniam nulla harum dolorem commodi id? Earum, rerum? Placeat, quidem voluptatum magni dolores eaque qui natus ad! Ipsum ea quia aperiam minus, deserunt recusandae soluta id animi cumque ab optio dolor quidem perspiciatis maxime nam totam non quae. In, deserunt sapiente. Voluptas inventore temporibus aspernatur itaque nisi labore mollitia, ipsam sapiente et necessitatibus nam.</h4>
    <h4>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Magnam porro hic quisquam molestiae consequatur. Quia eligendi perspiciatis perferendis voluptatibus earum excepturi cum blanditiis dolorem quod temporibus, quibusdam deserunt. Perspiciatis dignissimos natus excepturi praesentium corporis dolor error ea veritatis assumenda eveniet optio cupiditate, corrupti eaque odit ullam veniam nulla harum dolorem commodi id? Earum, rerum? Placeat, quidem voluptatum magni dolores eaque qui natus ad! Ipsum ea quia aperiam minus, deserunt recusandae soluta id animi cumque ab optio dolor quidem perspiciatis maxime nam totam non quae. In, deserunt sapiente. Voluptas inventore temporibus aspernatur itaque nisi labore mollitia, ipsam sapiente et necessitatibus nam.</h4>
    <h4>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Magnam porro hic quisquam molestiae consequatur. Quia eligendi perspiciatis perferendis voluptatibus earum excepturi cum blanditiis dolorem quod temporibus, quibusdam deserunt. Perspiciatis dignissimos natus excepturi praesentium corporis dolor error ea veritatis assumenda eveniet optio cupiditate, corrupti eaque odit ullam veniam nulla harum dolorem commodi id? Earum, rerum? Placeat, quidem voluptatum magni dolores eaque qui natus ad! Ipsum ea quia aperiam minus, deserunt recusandae soluta id animi cumque ab optio dolor quidem perspiciatis maxime nam totam non quae. In, deserunt sapiente. Voluptas inventore temporibus aspernatur itaque nisi labore mollitia, ipsam sapiente et necessitatibus nam.</h4>

  </Wrapper>
</template>

<script lang="ts">
import { defineComponent } from 'vue';
import SpotifyWebApi from "spotify-web-api-js"
import { getTokenFromResponse } from "../api/spotify"
import Wrapper from "./Wrapper.vue"
const spotify = new SpotifyWebApi()
export default defineComponent({
  name: 'Main',
  components: {
    Wrapper
  },
  setup() {
    const hash: any = getTokenFromResponse()
    window.location.hash = ""
    const _token = hash.access_token

    if (_token) {
      sessionStorage.setItem("token", _token)
      spotify.setAccessToken(_token)

      spotify.getMe().then(user => {
        sessionStorage.setItem("user", JSON.stringify(user))
      })
    }
  }
});
</script>
